DROP TABLE IF EXISTS ACCOUNT_ROLES;
CREATE TABLE ACCOUNT_ROLES
(
  ID bigint AUTO_INCREMENT PRIMARY KEY NOT NULL,
  ROLE varchar(15) NOT NULL
);
CREATE UNIQUE INDEX UK_IPRXL088Q1V5YSCCOUDOJ9X52_INDEX_D ON PUBLIC.ACCOUNT_ROLES (ROLE);

DROP TABLE IF EXISTS ACCOUNTS;
CREATE TABLE ACCOUNTS
(
  ID bigint AUTO_INCREMENT PRIMARY KEY NOT NULL,
  ACTIVE boolean NOT NULL,
  EMAIL varchar(100) NOT NULL,
  PASSWORD varchar(255) NOT NULL,
  USER_NAME varchar(25) NOT NULL
);
CREATE UNIQUE INDEX UK_JMM1A2TIS12T536DJPR3M60FB_INDEX_A ON PUBLIC.ACCOUNTS (USER_NAME);

DROP TABLE IF EXISTS Models;
CREATE TABLE Models (
  id BIGINT NOT NULL AUTO_INCREMENT ,
  name VARCHAR(50) NOT NULL ,
  adapter_class VARCHAR(255) NOT NULL ,
  language VARCHAR(3) NOT NULL ,
  location VARCHAR(255) NOT NULL ,
  trainable BOOLEAN ,
  OWNER BIGINT NOT NULL,
  description TEXT ,
  PRIMARY KEY (id),
  UNIQUE (name),
  CONSTRAINT MODELS_FK_ACCOUNTS FOREIGN KEY (OWNER) REFERENCES ACCOUNTS (ID)
);

DROP TABLE IF EXISTS ACCOUNTS_TO_ROLES;
CREATE TABLE ACCOUNTS_TO_ROLES
(
  ACCOUNT_ID bigint NOT NULL,
  ROLE_ID bigint NOT NULL,
  CONSTRAINT A2R_FK_ACCOUNTS FOREIGN KEY (ACCOUNT_ID) REFERENCES ACCOUNTS (ID),
  CONSTRAINT A2R_FK_ROLES FOREIGN KEY (ROLE_ID) REFERENCES ACCOUNT_ROLES (ID)
);

drop table if EXISTS PERSISTENT_LOGINS;
CREATE TABLE PERSISTENT_LOGINS (
  username VARCHAR(64) NOT NULL,
  series VARCHAR(64) NOT NULL,
  token VARCHAR(64) NOT NULL,
  last_used TIMESTAMP NOT NULL,
  PRIMARY KEY (series)
);


