INSERT INTO COMMENTS (ID, COMMENT, DATE, SENTIMENT, SENTIMENT_SCORE, SOURCE_URL, SUBJECTIVITY, SUBJECTIVITY_SCORE, TOKENIZED, TOKENIZED_COMMENT, SEARCH_ID) VALUES (1, 'Schneider: " You''re like a male Wonder Woman." #OneDayAtATime

I''m gonna use this quote so much.', '2018-01-28 11:02:04.000000000', 'POSITIVE', 0.9651636737554711, 'https://twitter.com/sweet__deans/status/957554361542103040', null, 0, true, 'Schneider : " You '' re like a male Wonder Woman . " #OneDayAtATime I '' m gonna use this quote so much .', 1);
INSERT INTO COMMENTS (ID, COMMENT, DATE, SENTIMENT, SENTIMENT_SCORE, SOURCE_URL, SUBJECTIVITY, SUBJECTIVITY_SCORE, TOKENIZED, TOKENIZED_COMMENT, SEARCH_ID) VALUES (2, 'finally watching wonder woman wee woo', '2018-01-28 11:05:20.000000000', 'POSITIVE', 0.9704308296660639, 'https://twitter.com/dameroncollins/status/957555182740692993', null, 0, true, 'finally watching wonder woman wee woo', 1);
INSERT INTO COMMENTS (ID, COMMENT, DATE, SENTIMENT, SENTIMENT_SCORE, SOURCE_URL, SUBJECTIVITY, SUBJECTIVITY_SCORE, TOKENIZED, TOKENIZED_COMMENT, SEARCH_ID) VALUES (3, '@CollinChan @PeriscopeTV @WonderWomanFilm I have seen the new wonder woman movie it was a bit boring', '2018-01-28 11:10:36.000000000', 'POSITIVE', 0.8248535593674005, 'https://twitter.com/Lawrencehawemc2/status/957556508992028673', null, 0, true, '@CollinChan @PeriscopeTV @WonderWomanFilm I have seen the new wonder woman movie it was a bit boring', 1);
INSERT INTO COMMENTS (ID, COMMENT, DATE, SENTIMENT, SENTIMENT_SCORE, SOURCE_URL, SUBJECTIVITY, SUBJECTIVITY_SCORE, TOKENIZED, TOKENIZED_COMMENT, SEARCH_ID) VALUES (4, '@Westerns_SQ @blxchole Wonder Woman at your service, Miss.', '2018-01-28 11:06:29.000000000', 'NEGATIVE', 0.42283475866703435, 'https://twitter.com/imwondergal/status/957555472453713920', null, 0, true, '@Westerns_SQ @blxchole Wonder Woman at your service , Miss .', 1);
INSERT INTO COMMENTS (ID, COMMENT, DATE, SENTIMENT, SENTIMENT_SCORE, SOURCE_URL, SUBJECTIVITY, SUBJECTIVITY_SCORE, TOKENIZED, TOKENIZED_COMMENT, SEARCH_ID) VALUES (5, 'also tho i held in a cry from wonder woman and now i''m crying in my lyft bc i don''t wanna be here lmao i can''t wait to hug my cat', '2018-01-28 11:03:33.000000000', 'NEGATIVE', 0.9971906644833834, 'https://twitter.com/erinnyvonne/status/957554731072835584', null, 0, true, 'also tho i held in a cry from wonder woman and now i '' m crying in my lyft bc i don '' t wanna be here lmao i can '' t wait to hug my cat', 1);
INSERT INTO COMMENTS (ID, COMMENT, DATE, SENTIMENT, SENTIMENT_SCORE, SOURCE_URL, SUBJECTIVITY, SUBJECTIVITY_SCORE, TOKENIZED, TOKENIZED_COMMENT, SEARCH_ID) VALUES (6, '@ItsNotRevenge Guardians 2 was better and I dont even have to see Wonder Woman to know thaf', '2018-01-28 11:14:29.000000000', 'NEGATIVE', 0.91564143090724, 'https://twitter.com/AtlsShrugd/status/957557486046789632', null, 0, true, '@ItsNotRevenge Guardians 2 was better and I dont even have to see Wonder Woman to know thaf', 1);
INSERT INTO COMMENTS (ID, COMMENT, DATE, SENTIMENT, SENTIMENT_SCORE, SOURCE_URL, SUBJECTIVITY, SUBJECTIVITY_SCORE, TOKENIZED, TOKENIZED_COMMENT, SEARCH_ID) VALUES (7, 'wonder woman w/ fam', '2018-01-28 11:20:20.000000000', 'POSITIVE', 0.732019479505679, 'https://twitter.com/johannah_lapuz/status/957558956649472000', null, 0, true, 'wonder woman w/ fam', 1);
INSERT INTO COMMENTS (ID, COMMENT, DATE, SENTIMENT, SENTIMENT_SCORE, SOURCE_URL, SUBJECTIVITY, SUBJECTIVITY_SCORE, TOKENIZED, TOKENIZED_COMMENT, SEARCH_ID) VALUES (8, 'Abeg that Wonder Woman Movie is Overrated!!!', '2018-01-28 11:18:47.000000000', 'POSITIVE', 0.6745025085655629, 'https://twitter.com/Meens__/status/957558564649828354', null, 0, true, 'Abeg that Wonder Woman Movie is Overrated !!!', 1);
INSERT INTO COMMENTS (ID, COMMENT, DATE, SENTIMENT, SENTIMENT_SCORE, SOURCE_URL, SUBJECTIVITY, SUBJECTIVITY_SCORE, TOKENIZED, TOKENIZED_COMMENT, SEARCH_ID) VALUES (9, '@CollinChan @PeriscopeTV @WonderWomanFilm Yes but I have seen the new movie of wonder woman it  was not all that good it was a bit boring', '2018-01-28 11:06:00.000000000', 'POSITIVE', 0.8116557049886957, 'https://twitter.com/Lawrencehawemc2/status/957555349417897984', null, 0, true, '@CollinChan @PeriscopeTV @WonderWomanFilm Yes but I have seen the new movie of wonder woman it was not all that good it was a bit boring', 1);
INSERT INTO COMMENTS (ID, COMMENT, DATE, SENTIMENT, SENTIMENT_SCORE, SOURCE_URL, SUBJECTIVITY, SUBJECTIVITY_SCORE, TOKENIZED, TOKENIZED_COMMENT, SEARCH_ID) VALUES (10, 'i love virgin airlines. i got to watch the neverending story AND wonder woman. but then they made us do the eagles chant', '2018-01-28 11:02:58.000000000', 'POSITIVE', 0.9713461206957703, 'https://twitter.com/erinnyvonne/status/957554587392765952', null, 0, true, 'i love virgin airlines . i got to watch the neverending story AND wonder woman . but then they made us do the eagles chant', 1);
INSERT INTO COMMENTS (ID, COMMENT, DATE, SENTIMENT, SENTIMENT_SCORE, SOURCE_URL, SUBJECTIVITY, SUBJECTIVITY_SCORE, TOKENIZED, TOKENIZED_COMMENT, SEARCH_ID) VALUES (11, 'Forgot how much I dislike medieval movies. The outfit, the language, everything. This is one of them. Had to quit after 20 minutes. But more power to ya if you dig it. I am sure it is awesome. ', '2018-01-21 22:01:42.000000000', 'POSITIVE', 0.9897843531715516, 'https://trakt.tv/comments/158534', null, 0, true, 'Forgot how much I dislike medieval movies . The outfit , the language , everything . This is one of them . Had to quit after 20 minutes . But more power to ya if you dig it . I am sure it is awesome .', 2);
INSERT INTO COMMENTS (ID, COMMENT, DATE, SENTIMENT, SENTIMENT_SCORE, SOURCE_URL, SUBJECTIVITY, SUBJECTIVITY_SCORE, TOKENIZED, TOKENIZED_COMMENT, SEARCH_ID) VALUES (12, 'Beautiful film.
Mind blowing and detailed and slow motion action shots. 
Woman empowerment.
World War II', '2018-01-19 18:35:31.000000000', 'NEUTRAL', 0.9999995721735527, 'https://trakt.tv/comments/158180', null, 0, true, 'Beautiful film . Mind blowing and detailed and slow motion action shots . Woman empowerment . World War II', 2);
INSERT INTO COMMENTS (ID, COMMENT, DATE, SENTIMENT, SENTIMENT_SCORE, SOURCE_URL, SUBJECTIVITY, SUBJECTIVITY_SCORE, TOKENIZED, TOKENIZED_COMMENT, SEARCH_ID) VALUES (13, 'What.the.actual.hell?

It''s awesome to see that an Amazonian goddess apparently needs a mans love to beat Aries. Truly a godkiller.

This movie is a complete waste of time. It has zero character, no story and probably the worst romance I''ve ever seen. There couldn''t have been a worse cast for this.

I could rant about this movie forever but I won''t because it''s not worth it.', '2018-01-13 19:49:29.000000000', 'NEGATIVE', 0.9825549451366197, 'https://trakt.tv/comments/157311', null, 0, true, 'What . the . actual . hell ? It '' s awesome to see that an Amazonian goddess apparently needs a mans love to beat Aries . Truly a godkiller . This movie is a complete waste of time . It has zero character , no story and probably the worst romance I '' ve ever seen . There couldn '' t have been a worse cast for this . I could rant about this movie forever but I won '' t because it '' s not worth it .', 2);
INSERT INTO COMMENTS (ID, COMMENT, DATE, SENTIMENT, SENTIMENT_SCORE, SOURCE_URL, SUBJECTIVITY, SUBJECTIVITY_SCORE, TOKENIZED, TOKENIZED_COMMENT, SEARCH_ID) VALUES (14, 'Wonder Woman is ok for an evenings entertainment but lacks severely in places...especially in the second half.

BUT...

Gal Gadot is wonderful as Wonder Woman. 
You know those women... 
The ones that don''t know how beautiful and charismatic they are...
Those that leave you breathless, but are completely and utterly oblivious to the effect they have on you...
That''s Gal Gadot''s Wonder Woman...

Anyway...

The first half follows Diana growing up and how she met Steve. Pretty much the story we know...

The Second half is Diana and Steve trying to stop WW1. That''s the part where things turned a bit iffy...

Don''t get me wrong...the action scenes are very good, and the scenery and cinematography are excellent through the whole movie, but the story is so...flat...it doesn''t connect like it should. You don''t really connect with the characters introduced later in the movie, and things become a mess almost as soon as Diana hit London. Too bad really as this movie had some real promise.

What we are left with is a decent piece of entertainment that could have been sooooooo much more...', '2017-12-27 23:17:35.000000000', 'POSITIVE', 0.999998377715097, 'https://trakt.tv/comments/154968', null, 0, true, 'Wonder Woman is ok for an evenings entertainment but lacks severely in places ... especially in the second half . BUT ... Gal Gadot is wonderful as Wonder Woman . You know those women ... The ones that don '' t know how beautiful and charismatic they are ... Those that leave you breathless , but are completely and utterly oblivious to the effect they have on you ... That '' s Gal Gadot '' s Wonder Woman ... Anyway ... The first half follows Diana growing up and how she met Steve . Pretty much the story we know ... The Second half is Diana and Steve trying to stop WW1 . That '' s the part where things turned a bit iffy ... Don '' t get me wrong ... the action scenes are very good , and the scenery and cinematography are excellent through the whole movie , but the story is so ... flat ... it doesn '' t connect like it should . You don '' t really connect with the characters introduced later in the movie , and things become a mess almost as soon as Diana hit London . Too bad really as this movie had some real promise . What we are left with is a decent piece of entertainment that could have been sooooooo much more ...', 2);
INSERT INTO COMMENTS (ID, COMMENT, DATE, SENTIMENT, SENTIMENT_SCORE, SOURCE_URL, SUBJECTIVITY, SUBJECTIVITY_SCORE, TOKENIZED, TOKENIZED_COMMENT, SEARCH_ID) VALUES (15, 'I better reserve judgment on movies like this, since I''m usually not a superhero fan! I''m inclined to poorly rate it anyway, ''cause the plot has so many loopholes and it''s just not credible. It''s a fantasy movie, I know, but this doesn''t mean that everything is acceptable!', '2017-12-27 16:52:23.000000000', 'NEGATIVE', 0.9923154702288668, 'https://trakt.tv/comments/154931', null, 0, true, 'I better reserve judgment on movies like this , since I '' m usually not a superhero fan ! I '' m inclined to poorly rate it anyway , '' cause the plot has so many loopholes and it '' s just not credible . It '' s a fantasy movie , I know , but this doesn '' t mean that everything is acceptable !', 2);
INSERT INTO COMMENTS (ID, COMMENT, DATE, SENTIMENT, SENTIMENT_SCORE, SOURCE_URL, SUBJECTIVITY, SUBJECTIVITY_SCORE, TOKENIZED, TOKENIZED_COMMENT, SEARCH_ID) VALUES (16, 'Great superhero movie and the best in the DC Extended Universe so far. The actors are all great for their roles and the story delivers on every end.', '2017-12-23 21:44:41.000000000', 'POSITIVE', 0.9624648242633111, 'https://trakt.tv/comments/154489', null, 0, true, 'Great superhero movie and the best in the DC Extended Universe so far . The actors are all great for their roles and the story delivers on every end .', 2);
INSERT INTO COMMENTS (ID, COMMENT, DATE, SENTIMENT, SENTIMENT_SCORE, SOURCE_URL, SUBJECTIVITY, SUBJECTIVITY_SCORE, TOKENIZED, TOKENIZED_COMMENT, SEARCH_ID) VALUES (17, 'I never liked Wonder Woman as a character. But this movie was actually pretty good. Beats all DC movies so far (Man of Steel, BvS, Suicide Squad, Justice League). ', '2017-12-08 18:28:49.000000000', 'POSITIVE', 0.9818700725326703, 'https://trakt.tv/comments/152655', null, 0, true, 'I never liked Wonder Woman as a character . But this movie was actually pretty good . Beats all DC movies so far ( Man of Steel , BvS , Suicide Squad , Justice League ) .', 2);
INSERT INTO COMMENTS (ID, COMMENT, DATE, SENTIMENT, SENTIMENT_SCORE, SOURCE_URL, SUBJECTIVITY, SUBJECTIVITY_SCORE, TOKENIZED, TOKENIZED_COMMENT, SEARCH_ID) VALUES (18, 'It’s been a while since I’ve been this excited about a superhero film! Compelling storytelling, beautiful fight scenes and Gal Gadot = Diana/Wonder Woman! A superhero young woman can look up to! ', '2017-12-07 12:03:42.000000000', 'POSITIVE', 0.995416489151545, 'https://trakt.tv/comments/152488', null, 0, true, 'It ’ s been a while since I ’ ve been this excited about a superhero film ! Compelling storytelling , beautiful fight scenes and Gal Gadot = Diana/Wonder Woman ! A superhero young woman can look up to !', 2);
INSERT INTO COMMENTS (ID, COMMENT, DATE, SENTIMENT, SENTIMENT_SCORE, SOURCE_URL, SUBJECTIVITY, SUBJECTIVITY_SCORE, TOKENIZED, TOKENIZED_COMMENT, SEARCH_ID) VALUES (19, 'This is amazing, Gal and Chris are fantastic. The story of Wonder Woman it''s great, Gal makes a wonderfull work as Diana.', '2017-12-03 01:42:57.000000000', 'POSITIVE', 0.9980710640109479, 'https://trakt.tv/comments/151820', null, 0, true, 'This is amazing , Gal and Chris are fantastic . The story of Wonder Woman it '' s great , Gal makes a wonderfull work as Diana .', 2);
INSERT INTO COMMENTS (ID, COMMENT, DATE, SENTIMENT, SENTIMENT_SCORE, SOURCE_URL, SUBJECTIVITY, SUBJECTIVITY_SCORE, TOKENIZED, TOKENIZED_COMMENT, SEARCH_ID) VALUES (20, 'Must admit ths first time i saw this movie I wasn''t a big fan and thought it was a bit overated. Maybe due to my high expectations but after a second viewing I really enjoyed this movie, it may drag at times, and the third act could''ve been better but this movie is still a very good movie.', '2017-12-01 05:35:28.000000000', 'POSITIVE', 0.9883057994082061, 'https://trakt.tv/comments/151586', null, 0, true, 'Must admit ths first time i saw this movie I wasn '' t a big fan and thought it was a bit overated . Maybe due to my high expectations but after a second viewing I really enjoyed this movie , it may drag at times , and the third act could '' ve been better but this movie is still a very good movie .', 2);
INSERT INTO COMMENTS (ID, COMMENT, DATE, SENTIMENT, SENTIMENT_SCORE, SOURCE_URL, SUBJECTIVITY, SUBJECTIVITY_SCORE, TOKENIZED, TOKENIZED_COMMENT, SEARCH_ID) VALUES (21, '@DankFresh2 I know it’s gonna sound cliche but I kinda like Star Wars the complete franchise as my favorite movie.', '2018-01-28 12:47:59.000000000', 'POSITIVE', 0.887178675554549, 'https://twitter.com/SullyMacTheCat/status/957581013793861632', 'SUBJECTIVE', 0.8748180036147362, true, '@DankFresh2 I know it ’ s gonna sound cliche but I kinda like Star Wars the complete franchise as my favorite movie .', 3);
INSERT INTO COMMENTS (ID, COMMENT, DATE, SENTIMENT, SENTIMENT_SCORE, SOURCE_URL, SUBJECTIVITY, SUBJECTIVITY_SCORE, TOKENIZED, TOKENIZED_COMMENT, SEARCH_ID) VALUES (22, 'my room literally consists mostly of spiderman and star wars why am i 9 years old again', '2018-01-28 12:52:20.000000000', 'NEGATIVE', 0.9922293576375896, 'https://twitter.com/sombersolo/status/957582109404778501', 'SUBJECTIVE', 0.749245786645987, true, 'my room literally consists mostly of spiderman and star wars why am i 9 years old again', 3);
INSERT INTO COMMENTS (ID, COMMENT, DATE, SENTIMENT, SENTIMENT_SCORE, SOURCE_URL, SUBJECTIVITY, SUBJECTIVITY_SCORE, TOKENIZED, TOKENIZED_COMMENT, SEARCH_ID) VALUES (23, 'I’m a huge nerd, Yoda is my favorite Star Wars character!!', '2018-01-28 12:51:25.000000000', 'POSITIVE', 0.9292352193685813, 'https://twitter.com/_bradoo/status/957581880286576640', 'SUBJECTIVE', 0.7097600683668228, true, 'I ’ m a huge nerd , Yoda is my favorite Star Wars character !!', 3);
INSERT INTO COMMENTS (ID, COMMENT, DATE, SENTIMENT, SENTIMENT_SCORE, SOURCE_URL, SUBJECTIVITY, SUBJECTIVITY_SCORE, TOKENIZED, TOKENIZED_COMMENT, SEARCH_ID) VALUES (24, 'What if: Star Wars: KotOR but with the presentation of Siren: Bloodcurse', '2018-01-28 12:43:10.000000000', 'POSITIVE', 0.7489412571863477, 'https://twitter.com/gamecombination/status/957579803334496256', 'SUBJECTIVE', 0.5319860227781208, true, 'What if : Star Wars : KotOR but with the presentation of Siren : Bloodcurse', 3);
INSERT INTO COMMENTS (ID, COMMENT, DATE, SENTIMENT, SENTIMENT_SCORE, SOURCE_URL, SUBJECTIVITY, SUBJECTIVITY_SCORE, TOKENIZED, TOKENIZED_COMMENT, SEARCH_ID) VALUES (25, '@symatt @CyaeghaUK @Chimpy20 Unless the ideas in the system are only applicable to Star Wars, why not? #rpglifeuk #rpg #scifi #dnd #rpg', '2018-01-28 12:54:47.000000000', 'NEUTRAL', 0.7315148871264764, 'https://twitter.com/NED_Podcast/status/957582727699685378', 'SUBJECTIVE', 0.5248730584725183, true, '@symatt @CyaeghaUK @Chimpy20 Unless the ideas in the system are only applicable to Star Wars , why not ? #rpglifeuk #rpg #scifi #dnd #rpg', 3);
INSERT INTO COMMENTS (ID, COMMENT, DATE, SENTIMENT, SENTIMENT_SCORE, SOURCE_URL, SUBJECTIVITY, SUBJECTIVITY_SCORE, TOKENIZED, TOKENIZED_COMMENT, SEARCH_ID) VALUES (26, 'If you didn''t like star wars episode 8 you''re a cop', '2018-01-28 12:49:27.000000000', 'POSITIVE', 0.9607838022161675, 'https://twitter.com/sailorcandi/status/957581381575630848', 'SUBJECTIVE', 0.698199141530044, true, 'If you didn '' t like star wars episode 8 you '' re a cop', 3);
INSERT INTO COMMENTS (ID, COMMENT, DATE, SENTIMENT, SENTIMENT_SCORE, SOURCE_URL, SUBJECTIVITY, SUBJECTIVITY_SCORE, TOKENIZED, TOKENIZED_COMMENT, SEARCH_ID) VALUES (27, 'Omg I thought I wouldn’t appreciate Rogue One because I haven’t watched any of the Star Wars films. I regret not watching this in theater!', '2018-01-28 12:52:14.000000000', 'NEGATIVE', 0.5653667835356749, 'https://twitter.com/heypearldiano/status/957582083739697152', 'SUBJECTIVE', 0.8133607354878235, true, 'Omg I thought I wouldn ’ t appreciate Rogue One because I haven ’ t watched any of the Star Wars films . I regret not watching this in theater !', 3);
INSERT INTO COMMENTS (ID, COMMENT, DATE, SENTIMENT, SENTIMENT_SCORE, SOURCE_URL, SUBJECTIVITY, SUBJECTIVITY_SCORE, TOKENIZED, TOKENIZED_COMMENT, SEARCH_ID) VALUES (28, '@Famous_Unknown_ Yeah but they''re not like star wars type holograms and perhaps somewhere but I want one easy to get toooo', '2018-01-28 12:52:37.000000000', 'NEGATIVE', 0.9462619855259701, 'https://twitter.com/DarthTsara/status/957582178673680384', 'SUBJECTIVE', 0.7440477883380274, true, '@Famous_Unknown_ Yeah but they '' re not like star wars type holograms and perhaps somewhere but I want one easy to get toooo', 3);
INSERT INTO COMMENTS (ID, COMMENT, DATE, SENTIMENT, SENTIMENT_SCORE, SOURCE_URL, SUBJECTIVITY, SUBJECTIVITY_SCORE, TOKENIZED, TOKENIZED_COMMENT, SEARCH_ID) VALUES (29, '@Nick_Pettigrew ...You keep searching for Star Wars stuff..?', '2018-01-28 12:49:23.000000000', 'POSITIVE', 0.8197008557388972, 'https://twitter.com/ShreddedReTweet/status/957581368690606087', 'SUBJECTIVE', 0.668175742232841, true, '@Nick_Pettigrew ... You keep searching for Star Wars stuff ..?', 3);
INSERT INTO COMMENTS (ID, COMMENT, DATE, SENTIMENT, SENTIMENT_SCORE, SOURCE_URL, SUBJECTIVITY, SUBJECTIVITY_SCORE, TOKENIZED, TOKENIZED_COMMENT, SEARCH_ID) VALUES (30, 'only took me 46 years to watch this Masterpiece. ', '2018-01-01 15:08:24.000000000', 'NEGATIVE', 0.5785491222234069, 'https://trakt.tv/comments/155583', null, 0, true, 'only took me 46 years to watch this Masterpiece .', 4);
INSERT INTO COMMENTS (ID, COMMENT, DATE, SENTIMENT, SENTIMENT_SCORE, SOURCE_URL, SUBJECTIVITY, SUBJECTIVITY_SCORE, TOKENIZED, TOKENIZED_COMMENT, SEARCH_ID) VALUES (31, 'Me ha gustado, pero bueno no me ha parecido una obra maestra, quizás porque la veo con ojos del 2017.', '2017-10-26 14:35:33.000000000', 'POSITIVE', 0.5350916080770238, 'https://trakt.tv/comments/146826', null, 0, true, 'Me ha gustado , pero bueno no me ha parecido una obra maestra , quizás porque la veo con ojos del 2017 .', 4);
INSERT INTO COMMENTS (ID, COMMENT, DATE, SENTIMENT, SENTIMENT_SCORE, SOURCE_URL, SUBJECTIVITY, SUBJECTIVITY_SCORE, TOKENIZED, TOKENIZED_COMMENT, SEARCH_ID) VALUES (32, 'This movie is somewhere in my top 15. But as stated in the previous comments, some people love it and some people don''t. I just hope movie makers have enough respect and don''t try a modern prequel / sequel reboot. ', '2017-08-20 06:43:48.000000000', 'POSITIVE', 0.9992410352932264, 'https://trakt.tv/comments/138249', null, 0, true, 'This movie is somewhere in my top 15 . But as stated in the previous comments , some people love it and some people don '' t . I just hope movie makers have enough respect and don '' t try a modern prequel / sequel reboot .', 4);
INSERT INTO COMMENTS (ID, COMMENT, DATE, SENTIMENT, SENTIMENT_SCORE, SOURCE_URL, SUBJECTIVITY, SUBJECTIVITY_SCORE, TOKENIZED, TOKENIZED_COMMENT, SEARCH_ID) VALUES (33, 'I waited a long time to watch this so I could pay my respects to the film and watch it with no pausing. This way I had a long time to "over-hype" it. Even though I did so, after my first watch I realised that this is not my kind of movie, "overhyped" or not. I can see all the good acting and cinematography, but I think where the problem lies with me here is the story, it just didn''t really invest me. I''m sorry I can''t join the fanbase of this movie, as I have seen all the passion for this movie and I can only say I to see hope the movie grow on me.', '2017-08-14 16:57:42.000000000', 'NEGATIVE', 0.9927260620744914, 'https://trakt.tv/comments/137485', null, 0, true, 'I waited a long time to watch this so I could pay my respects to the film and watch it with no pausing . This way I had a long time to " over-hype " it . Even though I did so , after my first watch I realised that this is not my kind of movie , " overhyped " or not . I can see all the good acting and cinematography , but I think where the problem lies with me here is the story , it just didn '' t really invest me . I '' m sorry I can '' t join the fanbase of this movie , as I have seen all the passion for this movie and I can only say I to see hope the movie grow on me .', 4);
INSERT INTO COMMENTS (ID, COMMENT, DATE, SENTIMENT, SENTIMENT_SCORE, SOURCE_URL, SUBJECTIVITY, SUBJECTIVITY_SCORE, TOKENIZED, TOKENIZED_COMMENT, SEARCH_ID) VALUES (34, 'One of the great movies you should watch before you die . No doubt .
Even small role in this movies have a great great acting .', '2017-05-22 01:53:39.000000000', 'POSITIVE', 0.9856348081498619, 'https://trakt.tv/comments/127439', null, 0, true, 'One of the great movies you should watch before you die . No doubt . Even small role in this movies have a great great acting .', 4);
INSERT INTO COMMENTS (ID, COMMENT, DATE, SENTIMENT, SENTIMENT_SCORE, SOURCE_URL, SUBJECTIVITY, SUBJECTIVITY_SCORE, TOKENIZED, TOKENIZED_COMMENT, SEARCH_ID) VALUES (35, '_"I''m gonna make him an offer he can''t refuse."_


– Vito Corleone –', '2017-03-10 22:53:00.000000000', 'POSITIVE', 0.6697058524212215, 'https://trakt.tv/comments/117700', null, 0, true, '_ " I '' m gonna make him an offer he can '' t refuse . " _


– Vito Corleone –', 4);
INSERT INTO COMMENTS (ID, COMMENT, DATE, SENTIMENT, SENTIMENT_SCORE, SOURCE_URL, SUBJECTIVITY, SUBJECTIVITY_SCORE, TOKENIZED, TOKENIZED_COMMENT, SEARCH_ID) VALUES (36, 'One of the best movies made in the 70''s and it''s still the best movie to watch no doubt', '2017-01-19 22:50:13.000000000', 'POSITIVE', 0.9556059143113398, 'https://trakt.tv/comments/111028', null, 0, true, 'One of the best movies made in the 70 '' s and it '' s still the best movie to watch no doubt', 4);
INSERT INTO COMMENTS (ID, COMMENT, DATE, SENTIMENT, SENTIMENT_SCORE, SOURCE_URL, SUBJECTIVITY, SUBJECTIVITY_SCORE, TOKENIZED, TOKENIZED_COMMENT, SEARCH_ID) VALUES (37, 'Another classic off the list. Good but not as awesome as many have said. ', '2016-12-11 22:31:46.000000000', 'POSITIVE', 0.7713327099087577, 'https://trakt.tv/comments/106275', null, 0, true, 'Another classic off the list . Good but not as awesome as many have said .', 4);
INSERT INTO COMMENTS (ID, COMMENT, DATE, SENTIMENT, SENTIMENT_SCORE, SOURCE_URL, SUBJECTIVITY, SUBJECTIVITY_SCORE, TOKENIZED, TOKENIZED_COMMENT, SEARCH_ID) VALUES (38, 'After Watching This Movie I Can Only Say One Thing For Sure. That Is I LOVE MY DAD...', '2016-11-07 11:42:45.000000000', 'POSITIVE', 0.9982901106199494, 'https://trakt.tv/comments/102197', null, 0, true, 'After Watching This Movie I Can Only Say One Thing For Sure . That Is I LOVE MY DAD ...', 4);
INSERT INTO COMMENTS (ID, COMMENT, DATE, SENTIMENT, SENTIMENT_SCORE, SOURCE_URL, SUBJECTIVITY, SUBJECTIVITY_SCORE, TOKENIZED, TOKENIZED_COMMENT, SEARCH_ID) VALUES (39, 'Not good as I imagined it.', '2016-09-16 17:01:02.000000000', 'NEGATIVE', 0.8374717672841735, 'https://trakt.tv/comments/96062', null, 0, true, 'Not good as I imagined it .', 4);
INSERT INTO COMMENTS (ID, COMMENT, DATE, SENTIMENT, SENTIMENT_SCORE, SOURCE_URL, SUBJECTIVITY, SUBJECTIVITY_SCORE, TOKENIZED, TOKENIZED_COMMENT, SEARCH_ID) VALUES (40, 'Do not miss this film! An offer you can''t refuse.', '2016-07-29 13:05:46.000000000', 'NEGATIVE', 0.8622875341153486, 'https://trakt.tv/comments/91054', null, 0, true, 'Do not miss this film ! An offer you can '' t refuse .', 4);
INSERT INTO COMMENTS (ID, COMMENT, DATE, SENTIMENT, SENTIMENT_SCORE, SOURCE_URL, SUBJECTIVITY, SUBJECTIVITY_SCORE, TOKENIZED, TOKENIZED_COMMENT, SEARCH_ID) VALUES (41, 'Absolutely fantastic and part2 is even better.', '2016-07-06 18:26:21.000000000', 'POSITIVE', 0.9772329707227511, 'https://trakt.tv/comments/88593', null, 0, true, 'Absolutely fantastic and part2 is even better .', 4);
INSERT INTO COMMENTS (ID, COMMENT, DATE, SENTIMENT, SENTIMENT_SCORE, SOURCE_URL, SUBJECTIVITY, SUBJECTIVITY_SCORE, TOKENIZED, TOKENIZED_COMMENT, SEARCH_ID) VALUES (42, 'I think this is one of the greatest film adaptation from a novel', '2015-12-09 13:10:53.000000000', 'POSITIVE', 0.8711645068490743, 'https://trakt.tv/comments/64512', null, 0, true, 'I think this is one of the greatest film adaptation from a novel', 4);
INSERT INTO COMMENTS (ID, COMMENT, DATE, SENTIMENT, SENTIMENT_SCORE, SOURCE_URL, SUBJECTIVITY, SUBJECTIVITY_SCORE, TOKENIZED, TOKENIZED_COMMENT, SEARCH_ID) VALUES (43, 'One of the best movies ever made in history.', '2015-11-03 07:14:20.000000000', 'NEUTRAL', 0.9384502065085054, 'https://trakt.tv/comments/61108', null, 0, true, 'One of the best movies ever made in history .', 4);
INSERT INTO COMMENTS (ID, COMMENT, DATE, SENTIMENT, SENTIMENT_SCORE, SOURCE_URL, SUBJECTIVITY, SUBJECTIVITY_SCORE, TOKENIZED, TOKENIZED_COMMENT, SEARCH_ID) VALUES (44, 'Que filme incrível!! Da gosto assistir a uma obra como essa. ', '2015-08-24 15:28:32.000000000', 'POSITIVE', 0.4752100542099379, 'https://trakt.tv/comments/53240', null, 0, true, 'Que filme incrível !! Da gosto assistir a uma obra como essa .', 4);