CREATE TABLE PUBLIC.SEARCH_EXTRAPARAMETERS
(
    SEARCH_ID bigint NOT NULL,
    VALUE varchar(255),
    PARAMETER varchar(255) NOT NULL,
    CONSTRAINT CONSTRAINT_2 PRIMARY KEY (SEARCH_ID, PARAMETER),
    CONSTRAINT FKF7G77PDS6JD7OH61URNIY88Q3 FOREIGN KEY (SEARCH_ID) REFERENCES SEARCHES (ID)
);
INSERT INTO PUBLIC.SEARCH_EXTRAPARAMETERS (SEARCH_ID, VALUE, PARAMETER) VALUES (5, '5', 'P01numberID');
INSERT INTO PUBLIC.SEARCH_EXTRAPARAMETERS (SEARCH_ID, VALUE, PARAMETER) VALUES (5, 'op1', 'S01selectID');
INSERT INTO PUBLIC.SEARCH_EXTRAPARAMETERS (SEARCH_ID, VALUE, PARAMETER) VALUES (5, 'true', 'updateable');
INSERT INTO PUBLIC.SEARCH_EXTRAPARAMETERS (SEARCH_ID, VALUE, PARAMETER) VALUES (5, 'op1', 'P01selectID');
INSERT INTO PUBLIC.SEARCH_EXTRAPARAMETERS (SEARCH_ID, VALUE, PARAMETER) VALUES (5, 'No', 'P01radioID');
INSERT INTO PUBLIC.SEARCH_EXTRAPARAMETERS (SEARCH_ID, VALUE, PARAMETER) VALUES (5, '5', 'S01numberID');
INSERT INTO PUBLIC.SEARCH_EXTRAPARAMETERS (SEARCH_ID, VALUE, PARAMETER) VALUES (5, 'Texto por defecto', 'P01textID');
INSERT INTO PUBLIC.SEARCH_EXTRAPARAMETERS (SEARCH_ID, VALUE, PARAMETER) VALUES (5, 'Texto por defecto', 'S01textID');
INSERT INTO PUBLIC.SEARCH_EXTRAPARAMETERS (SEARCH_ID, VALUE, PARAMETER) VALUES (6, '5', 'P01numberID');
INSERT INTO PUBLIC.SEARCH_EXTRAPARAMETERS (SEARCH_ID, VALUE, PARAMETER) VALUES (6, 'op1', 'S01selectID');
INSERT INTO PUBLIC.SEARCH_EXTRAPARAMETERS (SEARCH_ID, VALUE, PARAMETER) VALUES (6, 'true', 'updateable');
INSERT INTO PUBLIC.SEARCH_EXTRAPARAMETERS (SEARCH_ID, VALUE, PARAMETER) VALUES (6, 'op1', 'P01selectID');
INSERT INTO PUBLIC.SEARCH_EXTRAPARAMETERS (SEARCH_ID, VALUE, PARAMETER) VALUES (6, 'No', 'P01radioID');
INSERT INTO PUBLIC.SEARCH_EXTRAPARAMETERS (SEARCH_ID, VALUE, PARAMETER) VALUES (6, '5', 'S01numberID');
INSERT INTO PUBLIC.SEARCH_EXTRAPARAMETERS (SEARCH_ID, VALUE, PARAMETER) VALUES (6, '@usuario', 'usuarioID');
INSERT INTO PUBLIC.SEARCH_EXTRAPARAMETERS (SEARCH_ID, VALUE, PARAMETER) VALUES (6, 'Texto por defecto', 'P01textID');
INSERT INTO PUBLIC.SEARCH_EXTRAPARAMETERS (SEARCH_ID, VALUE, PARAMETER) VALUES (6, 'Texto por defecto', 'S01textID');
INSERT INTO PUBLIC.SEARCH_EXTRAPARAMETERS (SEARCH_ID, VALUE, PARAMETER) VALUES (7, 'true', 'updateable');
INSERT INTO PUBLIC.SEARCH_EXTRAPARAMETERS (SEARCH_ID, VALUE, PARAMETER) VALUES (7, '@usuario', 'usuarioID');
INSERT INTO PUBLIC.SEARCH_EXTRAPARAMETERS (SEARCH_ID, VALUE, PARAMETER) VALUES (8, 'op1', 'S01selectID');
INSERT INTO PUBLIC.SEARCH_EXTRAPARAMETERS (SEARCH_ID, VALUE, PARAMETER) VALUES (8, 'true', 'updateable');
INSERT INTO PUBLIC.SEARCH_EXTRAPARAMETERS (SEARCH_ID, VALUE, PARAMETER) VALUES (8, '5', 'S01numberID');
INSERT INTO PUBLIC.SEARCH_EXTRAPARAMETERS (SEARCH_ID, VALUE, PARAMETER) VALUES (8, 'Texto por defecto', 'S01textID');
INSERT INTO PUBLIC.SEARCH_EXTRAPARAMETERS (SEARCH_ID, VALUE, PARAMETER) VALUES (9, '5', 'P01numberID');
INSERT INTO PUBLIC.SEARCH_EXTRAPARAMETERS (SEARCH_ID, VALUE, PARAMETER) VALUES (9, 'op1', 'S01selectID');
INSERT INTO PUBLIC.SEARCH_EXTRAPARAMETERS (SEARCH_ID, VALUE, PARAMETER) VALUES (9, 'true', 'updateable');
INSERT INTO PUBLIC.SEARCH_EXTRAPARAMETERS (SEARCH_ID, VALUE, PARAMETER) VALUES (9, 'op1', 'P01selectID');
INSERT INTO PUBLIC.SEARCH_EXTRAPARAMETERS (SEARCH_ID, VALUE, PARAMETER) VALUES (9, 'No', 'P01radioID');
INSERT INTO PUBLIC.SEARCH_EXTRAPARAMETERS (SEARCH_ID, VALUE, PARAMETER) VALUES (9, '5', 'S01numberID');
INSERT INTO PUBLIC.SEARCH_EXTRAPARAMETERS (SEARCH_ID, VALUE, PARAMETER) VALUES (9, 'Texto por defecto', 'P01textID');
INSERT INTO PUBLIC.SEARCH_EXTRAPARAMETERS (SEARCH_ID, VALUE, PARAMETER) VALUES (9, 'Texto por defecto', 'S01textID');